version: "2"

services:
  reaper-mongo:
    image: mongo
    ports:
      - "27017:27017"

  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.10.1.0-2
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 'kafka'
#      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: 'files.obis.datasets:1:1'
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  reaper:
    build: .
    ports:
      - "8080:8080"
    links:
      - reaper-mongo

  console-downstream-consumer:
      image: wurstmeister/kafka:0.10.1.0-2
      command: /opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic files.obis.datasets --from-beginning
      links:
        - kafka:kafka
